### ISSUE TITLE
Git push to heroku

### ISSUE THREAD

**Issue by rickyhopkins** [actions/heroku#10]
I am trying to deploy to heroku with github actions using actions/heroku@master. I am not using docker so the standard directions for the heroku action does not really apply to me.

My current flow is:

```yml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: set remote
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: git:remote -a my-app
    - name: push
      run: git subtree push --prefix server heroku master
```

It seems to login just fine and it adds the remote but then it fails when I try to push to heroku with the following message:

`fatal: could not read Username for 'https://git.heroku.com': No such device or address`

Which seems strange because the heroku login command should be adding my credentials to the .netrc file.

**Comment by deniscostadsc** [comment]
Hi,

@rickyhopkins, I'm having same problem here. Did you work around this in a clever way?

**Comment by rickyhopkins** [comment]
Hey @deniscostadsc,

Nope, my project does not change too often so I have resorted to a manual deploy until I can get this working.

The only workaround that I found was [here](https://medium.com/@michaelekpang/creating-a-ci-cd-pipeline-using-github-actions-b65bb248edfe) which suggests adding the Heroku remote manually with the API key injected in like so:

```yml
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f
```

I did not test this myself but I can't see why it wouldn't work it just feels like a bit of a hack to me.

Hope that helps.

**Comment by karimsa** [comment]
You don’t need the remote step so for my project, this is the solution I’m using:

```yaml
  - name: Deploy to production
     run: |
       git push https://heroku:$HEROKU_API_KEY@git.heroku.com/<heroku-project>.git master
```
